/*	--------------------------------------------------
	@license

	Emphasis
	by Michael Donohoe (@donohoe)
	https://github.com/NYTimes/Emphasis
	http://open.blogs.nytimes.com/2011/01/10/emphasis-update-and-source/

	- - - - - - - - - -

	Copyright (C) 2011 The New York Times (http://www.nytimes.com)

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.

	-------------------------------------------------- */
	(function(a,b){"function"===typeof define&&define.amd?define([],b):"object"===typeof module&&module.exports?module.exports=b():(a.Emphasis=b(),document.addEventListener("DOMContentLoaded",function(){a.Emphasis.init()},!0))})(this,function(){return{init:function(){this.config();this.vu=this.s=this.h=this.p=this.pl=!1;this.kh="|";this.addCSS();this.readHash();document.addEventListener("keydown",this.keydown)},config:function(){this.paraSelctors=document.querySelectorAll("#article-content p");this.classReady=
	"emReady";this.classActive="emActive";this.classHighlight="emHighlight";this.classInfo="emInfo";this.classAnchor="emAnchor";this.classActiveAnchor="emActiveAnchor"},addCSS:function(){var a=document.createElement("style");a.setAttribute("type","text/css");var b="p."+this.classActive+" span { background-color:#f2f4f5; } p span."+this.classHighlight+" { background-color:#fff0b3; } span."+this.classInfo+" { position:absolute; margin:-1px 0px 0px -8px; padding:0; font-size:10px; background-color: transparent !important} span."+
	this.classInfo+" a { text-decoration: none; } a."+this.classActiveAnchor+" { color: #000; font-size: 11px; }";try{a.innerHTML=b}catch(c){a.styleSheet.cssText=b}document.getElementsByTagName("head")[0].appendChild(a)},readHash:function(){var a=decodeURI(location.hash),b=!1,c=[],d={},e,f,g;if(0>a.indexOf("[")&&0>a.indexOf("]")){if(f=/[ph][0-9]+|s[0-9,]+|[0-9]/g,a)for(;null!==(e=f.exec(a));)if(g=e[0].substring(0,1),e=e[0].substring(1),"p"===g)b=parseInt(e,10);else if("h"===g)c.push(parseInt(e,10));else{e=
	e.split(",");for(g=0;g<e.length;g++)e[g]=parseInt(e[g],10);d[c[c.length-1]]=e}}else if(b=a.match(/p\[([^[\]]*)\]/),g=a.match(/h\[([^[\]]*)\]/),b=b&&0<b.length?b[1]:!1,a=g&&0<g.length?g[1]:!1)for(a=a.match(/[a-zA-Z]+(,[0-9]+)*/g),g=0;g<a.length;g++)if(e=a[g].split(","),f=e[0],f=this.findKey(f).index,void 0!==f){c.push(parseInt(f,10)+1);e.shift();if(0<e.length)for(f=1;f<e.length;f++)e[f]=parseInt(e[f],10);d[c[c.length-1]]=e}this.p=b;this.h=c;this.s=d;this.goAnchor(b);this.goHighlight(c,d)},keydown:function(a){var b=
	Emphasis;b.kh=b.kh+a.keyCode+"|";-1<b.kh.indexOf("|16|16|")&&(b.vu=b.vu?!1:!0,b.paragraphInfo(b.vu));setTimeout(function(){b.kh="|"},500)},paragraphList:function(){if(this.pl&&0<this.pl.list.length)return this.pl;var a=this,b=[],c=[],d=0,e=this.paraSelctors.length,f,g,h;for(f=0;f<e;f++)g=this.paraSelctors[f],0<(g.innerText||g.textContent||"").length&&(h=a.createKey(g),b.push(g),c.push(h),g.setAttribute("data-key",h),g.setAttribute("data-num",d),g.addEventListener("click",function(b){a.paragraphClick(b)}),
	d++);return this.pl={list:b,keys:c}},paragraphClick:function(a){if(this.vu){var b=Emphasis,c=!1,d="P"===a.currentTarget.nodeName?a.currentTarget:!1,e="SPAN"===a.target.nodeName?a.target:!1,f="A"===a.target.nodeName?a.target:!1;f&&!b.hasClass(f,b.classActiveAnchor)&&(b.updateAnchor(f),c=!0,a.preventDefault());if(d||e){if(b.hasClass(d,b.classReady))b.hasClass(d,b.classActive)||!e||b.hasClass(e,b.classHighlight)?(b.hasClass(d,b.classActive)||(b.removeAllWithClass(b.classActive),b.addClass(d,b.classActive)),
	e&&(b.toggleClass(e,b.classHighlight),c=!0)):(b.removeAllWithClass(b.classActive),b.addClass(d,b.classActive));else{c=this.getSentences(d);a=c.length;for(e=0;e<a;e++)c[e]="<span data-num='"+(e+1)+"'>"+this.rtrim(c[e])+"</span>";c=c.join(". ").replace(/__DOT__/g,".").replace(/<\/span>\./g,".</span>");e=c.substring(c.length-8).charCodeAt(0);-1==="|8221|63|46|41|39|37|34|33|".indexOf(e)&&(c+=".");d.innerHTML=c;d.setAttribute("data-sentences",a);this.removeAllWithClass(b.classActive);this.addClass(d,
	b.classActive);this.addClass(d,b.classReady);c=!0}c&&this.updateURLHash()}else d.className.replace(b.classActive,"")}},paragraphInfo:function(a){var b,c,d,e,f;if(a){if(a=document.querySelectorAll("span."+this.classInfo),0===a.length)for(b=this.paragraphList(),a=b.list.length,c=0;c<a;c++)if(d=b.list[c]||!1)e=b.keys[c],f=e===this.p?" "+this.classActiveAnchor:"",d.innerHTML="<span class='"+this.classInfo+"'><a class='"+this.classAnchor+f+"' href='#p["+e+"]' data-key='"+e+"' title='Link to "+this.ordinal(c+
	1)+" paragraph'>&para;</a></span>"+d.innerHTML}else{b=document.querySelectorAll("span."+this.classInfo);a=b.length;for(c=0;c<a;c++)this.removeFromDOM(b[c]);this.removeAllWithClass(this.classActive)}},updateAnchor:function(a){this.p=a.getAttribute("data-key");this.removeAllWithClass(this.classActiveAnchor);this.addClass(a,this.classActiveAnchor)},updateURLHash:function(){var a="h[",b=document.querySelectorAll("p.emReady"),c=b.length,d,e,f,g,h;for(d=0;d<c;d++)if(e=b[d].getAttribute("data-key"),this.hasClass(b[d],
	this.classHighlight))a+=","+e;else if(f=b[d].querySelectorAll("span."+this.classHighlight),g=f.length,h=b[d].getAttribute("data-sentences"),0<g&&(a+=","+e),h!==g)for(e=0;e<g;e++)a+=","+f[e].getAttribute("data-num");a=((this.p?"p["+this.p+"],":"")+(a.replace("h[,","h[")+"]")).replace(",h[]","").replace("h[]","");location.hash=a},createKey:function(a){var b="";a=(a.innerText||a.textContent||"").replace(/[^a-z\. ]+/gi,"");var c,d;if(a&&1<a.length&&(c=this.getSentences(a),0<c.length))for(a=this.cleanArray(c[0].replace(/[\s\s]+/gi,
	" ").split(" ")).slice(0,3),c=this.cleanArray(c[c.length-1].replace(/[\s\s]+/gi," ").split(" ")).slice(0,3),a=a.concat(c),c=6<a.length?6:a.length,d=0;d<c;d++)b+=a[d].substring(0,1);return b},findKey:function(a){var b=this.paragraphList(),c=b.keys.length,d=!1,e=!1,f,g,h;for(f=0;f<c;f++){if(a===b.keys[f])return{index:f,elm:b.list[f]};d||(g=this.lev(a.slice(0,3),b.keys[f].slice(0,3)),h=this.lev(a.slice(-3),b.keys[f].slice(-3)),3>g+h&&(d=f,e=b.list[f]))}return{index:d,elm:e}},goAnchor:function(a){if(a){var b=
	isNaN(a)?this.findKey(a).elm:this.paragraphList().list[a-1]||!1;b&&setTimeout(function(){window.scrollTo(0,b.offsetTop)},499)}},goHighlight:function(a,b){if(a){var c=a.length,d,e,f,g,h,l,k,m,n;for(d=0;d<c;d++)if(e=this.paragraphList().list[a[d]-1]||!1){f=b[a[d].toString()]||!1;g=!f||0===f.length;h=this.getSentences(e);l=h.length;for(k=0;k<l;k++)h[k]="<span data-num='"+(k+1)+"'>"+h[k]+"</span>";for(k=0;k<l;k++)m=g?k:f[k]-1,(n=h[m]||!1)&&(h[m]=h[m].replace("<span","<span class='"+this.classHighlight+
	"'"));e.setAttribute("data-sentences",l);e.innerHTML=h.join(". ").replace(/__DOT__/g,".").replace(/<\/span>\./g,".</span>");this.addClass(e,"emReady")}}},getSentences:function(a){a="string"===typeof a?a:a.innerHTML;var b="A B C D E F G H I J K L M m N O P Q R S T U V W X Y Z etc oz cf viz sc ca Ave St Calif Mass Penn AK AL AR AS AZ CA CO CT DC DE FL FM GA GU HI IA ID IL IN KS KY LA MA MD ME MH MI MN MO MP MS MT NC ND NE NH NJ NM NV NY OH OK OR PA PR PW RI SC SD TN TX UT VA VI VT WA WI WV WY AE AA AP NYC GB IRL IE UK GB FR 0 1 2 3 4 5 6 7 8 9 www".split(" "),
	c=b.length,d;for(d=0;d<c;d++)a=a.replace(new RegExp(" "+b[d]+"\\.","g")," "+b[d]+"__DOT__");b="Mr Ms Mrs Miss Msr Dr Gov Pres Sen Prof Gen Rep St Messrs Col Sr Jf Ph Sgt Mgr Fr Rev No Jr Snr 0 1 2 3 4 5 6 7 8 9".split(" ");c=b.length;for(d=0;d<c;d++)a=a.replace(new RegExp(b[d]+"\\.","g"),b[d]+"__DOT__");b="aero asia biz cat com coop edu gov info int jobs mil mobi museum name net org pro tel travel xxx".split(" ");c=b.length;for(d=0;d<c;d++)a=a.replace(new RegExp("\\."+b[d],"g"),"__DOT__"+b[d]);return this.cleanArray(a.split(". "))},
	ordinal:function(a){var b=["th","st","nd","rd"],c=a%100;return a+(b[(c-20)%10]||b[c]||b[0])},lev:function(a,b){var c=a.length,d=b.length,e=[],f,g;e[0]=[];c<d&&(f=a,a=b,b=f,f=c,c=d,d=f);for(f=0;f<d+1;f++)e[0][f]=f;for(f=1;f<c+1;f++)for(e[f]=[],e[f][0]=f,g=1;g<d+1;g++)e[f][g]=this.smallest(e[f-1][g]+1,e[f][g-1]+1,e[f-1][g-1]+(a.charAt(f-1)===b.charAt(g-1)?0:1));return e[c][d]},smallest:function(a,b,c){return a<b&&a<c?a:b<a&&b<c?b:c},rtrim:function(a){return a.replace(/\s+$/,"")},cleanArray:function(a){var b=
	[],c;for(c=0;c<a.length;c++)a[c]&&0<a[c].replace(/ /g,"").length&&b.push(a[c]);return b},removeClass:function(a,b){a.className=a.className.replace(b,"")},removeAllWithClass:function(a){for(var b=document.querySelectorAll("."+a),c=b.length,d=0;d<c;d++)this.removeClass(b[d],a)},addClass:function(a,b){this.hasClass(a,b)||(a.className=a.className+" "+b)},hasClass:function(a,b){return-1===a.className.indexOf(b)?!1:!0},removeFromDOM:function(a){a.parentNode.removeChild(a)},toggleClass:function(a,b){this.hasClass(a,
	b)?this.removeClass(a,b):this.addClass(a,b)}}});
